export const material = [{
          value: 0,
          label: '全部'
        }, {
          value: 1,
          label: 'PP'
        }, {
          value: 2,
          label: 'HDPE'
        }, {
          value: 3,
          label: 'LLDPE'
        }, {
          value: 4,
          label: 'LDPE'
        }, {
          value: 5,
          label: 'PVC'
        }, {
          value: 6,
          label: 'ABS'
        }, {
          value: 7,
          label: 'HIPS'
        }, {
          value: 8,
          label: 'GPPS'
        }, {
          value: 9,
          label: 'PC'
        }, {
          value: 10,
          label: 'EVA'
        }, {
          value: 11,
          label: 'MDPE'
        }, {
          value: 12,
          label: 'PA'
        }, {
          value: 13,
          label: 'PBT'
        }, {
          value: 14,
          label: 'PET'
        }, {
          value: 15,
          label: 'POE'
        }]